name = "viewer-admin-dashboard"
main = "dist/worker.js"
compatibility_date = "2024-05-20"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "your-domain.com/*"

[env.staging]
workers_dev = true

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "VIEWER_KV"
id = "a6cd15df654547adaebd7d4e8624efd5"
preview_id = "a6cd15df654547adaebd7d4e8624efd5"

[[d1_databases]]
binding = "DB"
database_name = "viewerapps"
database_id = "21f45632-0762-4ac1-8d88-683387e84627"